name: chore_chart
description: Manage your household's collection of chores.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+beta

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the `CupertinoIcons` class for iOS style icons.
  cupertino_icons: ^1.0.8
  tinycolor2: ^3.0.1
  material_design_icons_flutter: 7.0.7296
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.8
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  package_info_plus: ^8.0.0
  mobx: ^2.3.3+2
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  build_test: ^2.2.2
  mobx_codegen: ^2.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/emoji_sponge.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts
